name: '${project.name}'
version: '${project.version}'
main: com.vexmi.escapadelabestia.EscapaBestia
load: POSTWORLD
author: Adrigamer2950
description: '${project.description}'

commands:
  edlb:
    aliases: ["escapadelabestia"]
    permission: edlb.*
    usage: "Usage: /edlb help"

permissions:
  edlb.*:
    default: op