name: '${project.name}'
version: '${project.version}'
description: '${project.description}'
main: org.vexmi.escapadelabestia.EscapaBestia
load: POSTWORLD
softdepend:
  - PlaceHolderAPI
depend:
  - Multiverse-Core
authors:
  - Adrigamer2950
  - SrBigos

commands:
  edlb:
    aliases: ["escapadelabestia"]
    usage: "Usage: /edlb help"
    permission: edlb.default

permissions:
  edlb.*:
    default: op
    children:
      edlb.admin:
        default: op
      edlb.default:
        default: true